export enum EnvKey {
  PROJECT_KEY = 'VITE_PROJECT_KEY',
  CLIENT_ID = 'VITE_CLIENT_ID',
  CLIENT_SECRET = 'VITE_CLIENT_SECRET',
  AUTH_URL = 'VITE_AUTH_URL',
  API_URL = 'VITE_API_URL',
  SCOPES = 'VITE_SCOPES',
}
